// Generated by CoffeeScript 1.6.3
(function() {
  var Mine;

  module.exports = function(game, opts) {
    return new Mine(game, opts);
  };

  Mine = function(game, opts) {
    this.game = game;
    opts = opts != null ? opts : {};
    return console.log("mine");
  };

}).call(this);
